(setq gc-cons-threshold 120000000)
(add-to-list 'load-path "~/.emacs.d/lisp")
(require 'tealeg--package)
(require 'tealeg--custom-file)
(require 'tealeg--backups)
(require 'tealeg--env)
(require 'tealeg--syntax)
(require 'tealeg--vc)
(require 'tealeg--lsp)
(require 'tealeg--comint)
(require 'tealeg--racket)
(require 'tealeg--markdown)
(require 'tealeg--yaml)
(require 'tealeg--go)
(require 'tealeg--racket)
(require 'tealeg--rust)
(require 'tealeg--eshell)
(require 'tealeg--carp)
(require 'tealeg--appearance)



(put 'downcase-region 'disabled nil)
(put 'upcase-region 'disabled nil)
